// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TaleScribe.Context;

#nullable disable

namespace TaleScribe.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260905095921_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("TaleScribe.Models.CombinedResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("SpeakerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SpeechRecognitionResultId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("T0")
                        .HasColumnType("INTEGER");

                    b.Property<long>("T1")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SpeechRecognitionResultId");

                    b.ToTable("CombinedResult");
                });

            modelBuilder.Entity("TaleScribe.Models.SpeechRecognitionResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Results");
                });

            modelBuilder.Entity("TaleScribe.Models.CombinedResult", b =>
                {
                    b.HasOne("TaleScribe.Models.SpeechRecognitionResult", null)
                        .WithMany("Combined")
                        .HasForeignKey("SpeechRecognitionResultId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TaleScribe.Models.SpeechRecognitionResult", b =>
                {
                    b.Navigation("Combined");
                });
#pragma warning restore 612, 618
        }
    }
}
